### ISSUE TITLE
cvmfs_repositories and cvmfs_http_proxy not passed to /etc/cvmfs/default.local

### ISSUE THREAD

**Issue by wdconinc** [eic/setup-cvmfs#1]
With `with: cvmfs_repositories: 'eic.opensciencegrid.org'` we would expect the file `/etc/cvmfs/default.local` to be filled with the correct CVMFS_REPOSITORIES. Currently we pass the inputs via the environment variables INPUT_CVMFS_REPOSITORIES, as outlines in the [docs](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions#inputs). However, that does not seem to work, e.g. https://github.com/eic/setup-cvmfs/runs/1288740472.

Possible ideas: environment is not passed to the setup-cvmfs.sh script, maybe we need to use [steps.run.env](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions#runsstepsenv) as follows:
```yaml
runs:
  using: "composite"
  steps: 
    - run: ${{ github.action_path }}/setup-cvmfs.sh
      shell: bash
      env:
        INPUT_CVMFS_REPOSITORIES: ${{ inputs.cvmfs_repositories }}
        INPUT_CVMFS_HTTP_PROXY: ${{ inputs.cvmfs_http_proxy }}
```
